
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    hikari:
      connection-timeout: 60000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.team5101.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
server:
  tomcat:
    max-http-post-size: -1

